name: "PicCap Issue"
labels: ["bug", "feature request", "documentation", "question"]
body:
  - type: checkboxes
    attributes:
      label: hyperion-webos
      description: |
            ⚠️ **ATTENTION:** This repository is only related to UI components.  
            Please create your issue at [hyperion-webos](https://github.com/webosbrew/hyperion-webos/issues) for problems regarding capture/video/ambilight.  
      options:
        - label: I belive that my issue is related to the PicCap UI and not to the [video capture backend](https://github.com/webosbrew/hyperion-webos)
          required: true
  - type: dropdown
    id: issueType
    attributes:
      label: "Issue Type"
      description: "What issue type describes your problem the best?"
      multiple: false
      options:
        - "UI does not work as intendend"
        - "This new UI feature does not exists"
        - "There is something missing in the documentation"
        - "I have a question"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.

            
