name: "PicCap feature request"
description: "This new UI feature does not exists and would be nice to have"
labels: ["feature request"]
body:
  - type: checkboxes
    attributes:
      label: PicCap related issues only 
      description: |
        ⚠️ **ATTENTION:** This repository contains only components related to the UI.  
        Please create your issue at [hyperion-webos](https://github.com/webosbrew/hyperion-webos/issues) if its related to capture/video/ambilight.  
      options:
        - label: I belive that my issue is related to the PicCap UI and not to the [video capture backend](https://github.com/webosbrew/hyperion-webos)
          required: true
        - label: I have checked [open and closed issues](https://github.com/TBSniller/piccap/issues?q=is%3Aissue%20state%3Aopen%20) to avoid duplicated issues
          required: true
        - label: Please check this box if we have a already existing backend option missing in PicCap UI
          required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "What feature do you want to have? Formly describe it."
      placeholder: "Switch color design to red would be nice"
      render: text
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: "Anything more to say?"
      placeholder: "Drag and drop images here if needed"
      render: text
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

            
