name: "PicCap Bug report"
description: "PicCap UI does not work as intendend"
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: PicCap related issues only 
      description: |
        ⚠️ **ATTENTION:** This repository contains only components related to the UI.  
        Please create your issue at [hyperion-webos](https://github.com/webosbrew/hyperion-webos/issues) if its related to capture/video/ambilight.  
      options:
        - label: I belive that my issue is related to the PicCap UI and not to the [video capture backend](https://github.com/webosbrew/hyperion-webos)
          required: true

  - type: textarea
    id: osinfo
    attributes:
      label: WebOS Information
      description: | 
        Please run `luna-send -f -n 1 'luna://com.webos.service.systemservice/osInfo/query' '{"parameters":["webos_manufacturing_version", "webos_release", "webos_build_datetime"]}'` on your TV and put the output in here
      render: json
      placeholder: |
        {
          "webos_release": "5.3.0",
          "webos_build_datetime": "20211202050112",
          "returnValue": true,
          "webos_manufacturing_version": "04.30.50"
        }
    validations:
      required: true
      
  - type: input
    id: piccap_version
    attributes:
      label: PicCap Version
      description: "Which version do you use? (Check top left corner in PicCap)"
      placeholder: "0.5.1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "What bug do you encounter? Formly describe it."
      placeholder: "The color of the app is changing to red randomly"
      render: text
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1. Open PicCap using magic remote
        2. Click x
        3. Click y
        ...
      render: text
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: "What should have happen instead?"
      placeholder: "The color of the app should stay at blue how it was set."
      render: text
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: "Please append screenshots or log output from PicCap's log tab."
      placeholder: "Just drag and drop your screenshots here"
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: "Anything more to say?"
      placeholder: "A workaround is to just hit the bulb button"
      render: text
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

            
